defmodule Tunez.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "artists_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :updated_by_id,
          references(:users,
            column: :id,
            name: "artists_updated_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:artists, "artists_created_by_id_fkey")

    drop constraint(:artists, "artists_updated_by_id_fkey")

    alter table(:artists) do
      remove :updated_by_id
      remove :created_by_id
    end
  end
end
